spring:
  profiles:
    active: production
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: development
server:
  port: 8080


---
spring:
  config:
    activate:
      on-profile: production

server:
  port: 8000


logging:
  file:
    path: /Users/liyang/var/logs
    name: readinglist.log

