spring:
  profiles:
    active: development
  jpa:
    defer-datasource-initialization: true
  thymeleaf:
    cache: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: development
server:
  port: 8080


---
spring:
  config:
    activate:
      on-profile: production

server:
  port: 8000


logging:
  file:
    path: /Users/liyang/var/logs
    name: readinglist.log

