spring:
  application:
    name: readinglist
  #  boot:
  #    admin:
  #      client:
  #        url: http://localhost:9091
  #  profiles:
  #    active: development
  jpa:
    defer-datasource-initialization: true
  thymeleaf:
    cache: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: INFO
#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always # health的详细信息

info:
  app:
    name: readlist
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831


---
spring:
  config:
    activate:
      on-profile: development
server:
  port: 8001


---
spring:
  config:
    activate:
      on-profile: production

server:
  port: 8000


logging:
  file:
    path: /Users/liyang/var/logs
    name: readinglist.log

