#!/bin/bash
# basic  -t 指定计时器，超时以非零退出状态码退出
#read -p "Enter your name:" first last
#echo "Checking data for $last, $first..."

## 不指定变量，使用REPLY环境变量
#read -p "Enter your name:"
#echo "Hello $REPLY, welcome..."

# -n 输入达到指定字符时自动退出
#read -n1 -p "Do u want to cotinue [Y/N]? " answer
#case $answer in
#Y | y) echo
#       echo "fine, continue on..." ;;
#N | n) echo
#       echo "OK, goodbye"
#       exit;; # 提前结束
#esac
#echo "This is the end of the script"

# read from a file with cat
count=1
cat test1 | while read line
do
  echo "Line $count:$line"
  count=$[ $count + 1 ]
done
echo "Finished processing the file"

# read from csv file
#input="users.csv"
#while IFS=',' read -r userid name
#do
#  echo "userid:$userid,name:$name"
#done < "$input"
