#!/bin/bash
#捕获信号
trap "echo 'sorry, i have trapped Ctrl-C'" SIGINT  #捕获SIGINT信号
trap "echo Googbye..." EXIT  #捕获退出信号
echo "test start"
count=1
while [ $count -le 20 ]
do
  echo "Loop #$count"
  sleep 1
  count=$[$count+1]
done

trap -- SIGINT #恢复信号默认行为，即终止脚本

count=1
while [ $count -le 20 ]
do
  echo "Second Loop #$count"
  sleep 1
  count=$[$count+1]
done
echo "test end"